workdir: /home/[user]/Data # data and analysis path/
codedir: ~/ambic-epigenome # path to this dir
reference: /mnt/ref/Cricetulus_griseus_picr.CriGri-PICR.dna.toplevel.nihIgG.fa
threads: 12 # available cores
