---
title: "ambic sigma aging study qc"
author: Isac Lee
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
#bibliography: master.bib
# set dir in the following function to the desired loc
mainfont: "DejaVu Sans" # Try out some font options if xelatex
titlefont: "DejaVu Sans" # Try out some font options if xelatex
---

```{r setup, eval=TRUE, include=FALSE, cache=F, message=F, warning=F, results="hide"}
rm(list=ls());gc()
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache = FALSE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```

```{r libs, eval=T, include=FALSE, cache=F, message=F, warning=F, results="hide"}
source("~/Code/ilee/plot/ilee_plot_utils.R")
library(bsseq)
```

```{r functions, include = F}
```


```{r read_data, eval = T, include = FALSE, cache=F }
dir <- "/kyber/Data/Nanopore/projects/ambic/sigma/methylation/mfreq"
fpaths <- system(paste("find",dir,"-name \"*txt.gz\""),intern=T)
labs <- sapply(strsplit(basename(fpaths),"[.]"),"[[",1)
samples <- sapply(strsplit(runs,"_"),"[[",1)
cells <- sapply(strsplit(labs,"Day"),"[[",1)
pd <- tibble(fpath = fpaths, label = labs, sample = samples, cell = cells)

# read data
bsobj <- read.bismark(pd$fpath,colData = pd)

# get methylation
meth <- getMeth(bsobj,type = "raw")
meth <- na.omit(meth)
nrow(meth)

# pca
meth.t <- t(meth)
pca.m <- prcomp(meth.t)
pca.tb <- as_tibble(pca.m$x[,1:6]) %>%
  bind_cols(pd)
```


```{r plot_pca, eval = T, echo = F, fig.height=3, fig.width=6, message=F, warning = F,results = 'hide', fig.show = 'show'}
# plot
g <- ggplot(pca.tb,aes(x = PC1, y = PC2, color = cell)) + geom_point()
plotter(g)
```
