---
title: "ambic sigma aging study qc"
author: Isac Lee
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
#bibliography: master.bib
# set dir in the following function to the desired loc
mainfont: "DejaVu Sans" # Try out some font options if xelatex
titlefont: "DejaVu Sans" # Try out some font options if xelatex
---

```{r setup, eval=TRUE, include=FALSE, cache=F, message=F, warning=F, results="hide"}
rm(list=ls());gc()
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache = FALSE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```

```{r libs, eval=T, include=FALSE, cache=F, message=F, warning=F, results="hide"}
#source("~/Code/ilee/plot/ilee_plot_utils.R")
source("/home/isac/Code/ilee/plot/ilee_plot_utils.R")
source("/home/isac/Code/nanopore-methylation-utilities/methylation_R_utils.R")
library(tidyverse)
library(bsseq)
library(dmrseq)

```

```{r functions, include = F}
```


```{r read_data, eval = T, include = FALSE, cache=F }
plotdir <- "/home/isac/Dropbox (Timp Lab)/Data/ambic/aging_study/methylation"
dir <- "/kyber/Data/Nanopore/projects/ambic/sigma/methylation/mfreq"
rawpath <- file.path(dir,"CHOZN.BSseq.rds")
bspath <- file.path(dir,"CHOZN.BSmooth.Rds")
#fpaths <- system(paste("find",dir,"-name \"*txt.gz\""),intern=T)
#labs <- sapply(strsplit(basename(fpaths),"[.]"),"[[",1)
#samples <- sapply(strsplit(labs,"_"),"[[",1)
#cells <- sapply(strsplit(labs,"Day"),"[[",1)
#days <- as.factor(as.numeric(sapply(strsplit(samples,"Day"),"[[",2)))
#pd <- tibble(fpath = fpaths, label = labs, sample = samples, cell = cells, day = days)

# read data
#bsobj <- read.bismark(pd$fpath,colData = pd)
bsobj <- readRDS(bspath)
pd <- pData(bsobj) %>% as_tibble()
pd$rep <- as.factor(sapply(strsplit(pd$label,"_"),"[[",2))
pd$day <- as.factor(sapply(strsplit(pd$sample,"Day"),"[[",2))
pData(bsobj) <- pd
```

```{r transgene}
keepi <- which(grepl("ambic",seqnames(bsobj)))
bs.trans <- bsobj[keepi,]
meth.trans <- getMeth(bs.trans)

meth.tb <- as_tibble(meth.trans)
colnames(meth.tb) <- pd$label
meth.tb <- meth.tb  %>%
  bind_cols(as_tibble(granges(bs.trans)) %>%
    dplyr::select(chrom = seqnames,pos = start)
  ) 

meth.gather <- meth.tb %>%
  gather(label,mfreq,-chrom,-pos)
meth.gather <- meth.gather %>%
  bind_cols(pd[match(meth.gather$label,pd$label),]) %>%
  dplyr::select(-fpath,-label1)

tsvpath <- file.path(plotdir,"CHO_agingstudy_transgene_methylation.tsv")
write_tsv(meth.gather,tsvpath)
  
```

```{r transgene_plot}
meth.hc <- meth.gather %>%
  filter(grepl("HC", chrom ))
meth.lc <- meth.gather %>%
  filter(grepl("LC", chrom ))
plotpath <- file.path(plotdir,"200527_transgene_methylation.pdf")
pdf(plotpath)
ggplot(meth.hc,aes( x = pos, y = mfreq, color = cell)) +
  facet_wrap(~day) +
  geom_smooth(span = 0.1, method = "loess",se = F) +
  geom_point(alpha = 0.2, size = 1)
dev.off()


```



