---
title: "ambic sigma aging study qc"
author: Isac Lee
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: xelatex
#bibliography: master.bib
# set dir in the following function to the desired loc
mainfont: "DejaVu Sans" # Try out some font options if xelatex
titlefont: "DejaVu Sans" # Try out some font options if xelatex
---

```{r setup, eval=TRUE, include=FALSE, cache=F, message=F, warning=F, results="hide"}
rm(list=ls());gc()
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache = FALSE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
```

```{r libs, eval=T, include=FALSE, cache=F, message=F, warning=F, results="hide"}
#source("~/Code/ilee/plot/ilee_plot_utils.R")
source("/home/isac/Code/ilee/plot/ilee_plot_utils.R")
source("/home/isac/Code/nanopore-methylation-utilities/methylation_R_utils.R")
library(tidyverse)
library(bsseq)
library(dmrseq)

```

```{r functions, include = F}
```


```{r read_data, eval = T, include = FALSE, cache=F }
plotdir <- "/home/isac/Dropbox (Timp Lab)/Data/ambic/aging_study/methylation"
dir <- "/kyber/Data/Nanopore/projects/ambic/sigma/methylation/mfreq"
rawpath <- file.path(dir,"CHOZN.BSseq.rds")
bspath <- file.path(dir,"CHOZN.BSmooth.Rds")
#fpaths <- system(paste("find",dir,"-name \"*txt.gz\""),intern=T)
#labs <- sapply(strsplit(basename(fpaths),"[.]"),"[[",1)
#samples <- sapply(strsplit(labs,"_"),"[[",1)
#cells <- sapply(strsplit(labs,"Day"),"[[",1)
#days <- as.factor(as.numeric(sapply(strsplit(samples,"Day"),"[[",2)))
#pd <- tibble(fpath = fpaths, label = labs, sample = samples, cell = cells, day = days)

# read data
#bsobj <- read.bismark(pd$fpath,colData = pd)
bsobj <- readRDS(bspath)
pd <- pData(bsobj) %>% as_tibble()
pd$rep <- as.factor(sapply(strsplit(pd$label,"_"),"[[",2))
pd$day <- as.factor(sapply(strsplit(pd$sample,"Day"),"[[",2))
pData(bsobj) <- pd
```

```{r preprocess, eval = T, include = FALSE, cache=F }
# let's preprocess the data
# filter out low coverage regions
bscov <- getCoverage(bsobj,type="Cov")
#cov.gather <- as_tibble(bscov) %>%
#  mutate(idx = seq(nrow(bscov))) %>%
#  gather(sampvid,cov,-idx)
## add in sample info - takes forever
#cov.gather$sampidx <- as.numeric(str_remove(cov.gather$sampvid,"V"))
#cov.gather$sample <- pd[cov.gather$sampidx,]$sample
#cov.sum <- cov.gather %>%
#  group_by(idx,sample) %>%
#  summarize(sum(cov))

# let's just do it simple
keepi <- which(DelayedMatrixStats::rowSums2(bscov == 0) == 0)
bs.keep <- bsobj[keepi,]

# remove na
m <- getMeth(bs.keep,type = "smooth")
keepi <- which(DelayedMatrixStats::rowSums2(is.na(m)) == 0)
which(is.na(m))

bs.keep <- bs.keep[keepi,]

```

```{r dmrseq, eval = T, include = FALSE, cache=F }
## try comparing between days
## doing all four at the same time, but I might have to do it one by one later depending on the result
#bp <- MulticoreParam(workers = 4,progressbar = TRUE)
#test <- "day"
#for (cond in unique(pd$cell)) {
#  indices <- which(pd$cell == cond)
#  bs.sub <- bs.keep[,indices]
#  candidates <- dmrseq(bs.sub,
#    cutoff = 0.05,
#    testCovariate = test,
#    BPPARAM = bp
#  )
#}
```

```{r bsseq, eval = T, include = FALSE, cache=F }
# try comparing between days
combos <- tibble(
  cell = rep(unique(pd$cell),each = 3),
  one = rep(c(30,60,90),5),
  two = 0
)
# let's get tstats first
tstats.list <- mclapply(mc.cores = 15,seq(nrow(combos)), function(i){
  combo <- combos[i,]
  indices <- which(pd$cell == combo$cell)
  onei <- intersect(indices,which(pd$day == combo$one))
  twoi <- intersect(indices,which(pd$day == combo$two))
  tstats <- BSmooth.tstat(bs.keep,
    group1 = onei, group2 = twoi,
    estimate.var = "group2",
    maxGap = 1e3
  )
  tstats
})
# let's plot the tstats
plotpath <- file.path(plotdir,"200527_tstats.pdf")
pdf(plotpath)
for (i in seq(nrow(combos))){
  tstat <- tstats.list[[i]]
  x <- tstat@stats
  y <- as_tibble(x[which(!is.na(x[,"tstat"])),])
  plt <- y %>%
    gather(what,val,tstat,tstat.corrected)
  lab <- paste(combos[i,],collapse=".")
  g <- ggplot(plt,aes(x = val,color = what)) +
    geom_density() +
    labs(title = lab)
  print(g)
}
dev.off()

# find DMRs using the tstats
dmrs.list <- mclapply(mc.cores = 15,tstats.list,function(x){
  dmrFinder(x,cutoff = c(-4,4))})
dmrs.all <- bind_rows(dmrs.list,.id = "compidx") %>%
  as_tibble() 
dmrs.all <- bind_cols(dmrs.all ,combos[dmrs.all$compidx,]) %>%
  mutate(one = as.factor(one))

dmrs.all %>%
  group_by(cell,one,direction) %>%
  summarize(n())

plotpath <- file.path(plotdir,"200527_dmrs_summary.pdf")
pdf(plotpath)
ggplot(dmrs.all,aes( x = cell, fill = one)) +
  geom_bar(position= "dodge")  +
  labs(x = "cell", y = "Count") +
  theme(axis.text.x = element_text(angle = -45,hjust = 0))
ggplot(dmrs.all,aes( x = one, fill = cell)) +
  geom_bar(position= "dodge")  +
  labs(x = "Day", y = "Count")
ggplot(dmrs.all,aes( x = one, fill = direction)) +
  facet_wrap(~cell) +
  geom_bar(position= "dodge") 
dev.off()

# summary per basepair
dmrs.perbp <- dmrs.all %>%
  group_by(cell,one,direction) %>%
  summarize( bp = sum(width))
plotpath <- file.path(plotdir,"200527_dmrs_summary_perbp.pdf")
pdf(plotpath)
ggplot(dmrs.perbp,aes( x = cell, fill = one, y = bp)) +
  geom_bar(position= "dodge", stat = "identity")  +
  labs(x = "Cell", y = "Basepairs") +
  theme(axis.text.x = element_text(angle = -45,hjust = 0))
ggplot(dmrs.perbp,aes( x = one, fill = cell, y = bp)) +
  geom_bar(position= "dodge", stat = "identity")  +
  labs(x = "Day", y = "Basepairs")
ggplot(dmrs.perbp,aes( x = one, fill = direction, y = bp)) +
  facet_wrap(~cell) +
  geom_bar(position= "dodge", stat = "identity")  +
  labs(x = "Day", y = "Basepairs")
dev.off()


# let's output dmrs
tsvpath <- file.path(plotdir,"CHO_aging_study_DMRs.tsv")
write_tsv(dmrs.all,tsvpath)

```
