---
title: "plasmid lengths"
author: "Isac Lee"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook: default
  pdf_document: default
mainfont: DejaVu Sans
titlefont: DejaVu Sans
---

```{r setup, eval=TRUE, include=FALSE, cache=F, message=F, warning=F, results="hide"}
rm(list=ls());gc()
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache = FALSE, warning = FALSE,
                      message = FALSE, cache.lazy = FALSE)
my_plot_hook <- function(x, options)
  paste("\n", knitr::hook_plot_tex(x, options), "\n")
knitr::knit_hooks$set(plot = my_plot_hook)
```

```{r libs, eval=T, include=FALSE, cache=F, message=F, warning=F, results="hide"}
source("/home/isac/Code/ilee/plot/ilee_plot_utils.R")
```

```{r length_plot, eval = T, echo = F, fig.height=2.5, fig.width=4, message=F, warning = F,results = 'hide', fig.show = 'show'}
fp <- "/home/isac/Dropbox/Data/ambic/capture/analysis/bothSIDES_lengths.txt"
data <- read_tsv(fp,col_names="length")

data.bin <- data %>%
  mutate(bin = round(length/1000)*1000) %>%
  group_by(bin) %>%
  summarize(n = n()) 
peak <- data.bin %>%
  filter( n == max(n)) %>%
  mutate(lab = paste("L =",bin))

ggplot(data.bin,aes(x = bin, y = n)) +
  geom_bar(stat = "identity", fill = pal[3]) +
  geom_text(inherit.aes = F, data = peak, mapping = aes(label = lab, x = bin, y = n + 10), hjust = 0.5) +
  lims( x = c(0, 30000)) +
  labs( x = "Read Length", y = "Count")

```